projects:
  app:
    schemaPath: backend/schemas/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
  database:
    schemaPath: backend/schemas/prisma.graphql
    extensions:
      prisma: backend/database/prisma.yml